kenya_keys/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KK.Models;
using System.Web.Routing;

namespace kenya_keys.Controllers
{
    public class BlogController : Controller
    {

		protected override void Initialize(RequestContext context) {
			// context.RouteData.Values["Admin"] 
			base.Initialize (context);
			ViewData["IsAdmin"] = context.HttpContext.Request.IsAuthenticated && User.IsInRole("admin") ? true : false;
		}

        /// <summary>
        /// Index
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="blogId"></param>
        /// <returns></returns>
        public ActionResult Edit(int? blogId = null)
        {
            if (User.Identity.IsAuthenticated == false)
            {
                Response.Redirect("~/Home/Index");
            }
            Blog blog = new Blog();
            if (blogId != null) { blog = Blog.Get(Convert.ToInt32(blogId)); }
			return View(blog);
        }

		/// <summary>
		/// Deletes a blog
		/// </summary>
		/// <param name="blogId">Blog identifier.</param>
		public JsonResult Delete(int blogId) {
			Blog blog = Blog.Delete (blogId);
			return Json (blog);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="blogId"></param>
		/// <returns></returns>
		public ActionResult View(int? blogId = null)
		{

			Blog blog = new Blog();
			if (blogId != null) {
				blog = Blog.Get (Convert.ToInt32 (blogId));
			} else {
				RedirectToAction ("Home", "Blog");
			}
			return View(blog); // PartialView to return Partial
		}


		public ActionResult List(int offset = 0, int limit = 5, int? total = null)
		{
			ViewData ["blogs"] = Blog.GetAll (offset, limit);
			if (total == null) {
				total = Blog.GetTotalCount ();
			}
			ViewData ["total"] = total;
			ViewData ["limit"] = limit;
			ViewData ["offset"] = offset;

			return PartialView();
		}

        [HttpPost]
		public JsonResult Save(string blog_description, string blog_title, string blog_hidden, string blog_html, string blog_start_date, string blog_end_date, int? blog_id = null) {
			Blog blog = new Blog();
			if (blog_id != null) {
				blog = Blog.Get (Convert.ToInt32 (blog_id));
				blog.BlogPostDate = DateTime.Now;
			} else {
				blog.BlogAuthor = User.Identity.Name;
			}
            
            blog.BlogDescription = blog_description;
            blog.BlogHidden = blog_hidden == "yes" ? true : false;
            blog.BlogTitle = blog_title;
            blog.BlogHtml = blog_html;
            if (blog_start_date.Length > 0) {
                blog.BlogStartDate = Convert.ToDateTime(blog_start_date);
            }
            if (blog_end_date.Length > 0) {
                blog.BlogEndDate = Convert.ToDateTime(blog_end_date);
            }

            blog.Save();
			return Json (blog);
        }
    }
}

kenya_keys/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;

namespace KK.Controllers
{
    public class HomeController : Controller
    {
		public KK.User user;
		public bool IsAdmin;
		protected override void Initialize(RequestContext context) {
			// context.RouteData.Values["Admin"] 
			base.Initialize (context);
			ViewData["IsAdmin"] = context.HttpContext.Request.IsAuthenticated && User.IsInRole("admin") ? true : false;
		}

        
		/// <summary>
		/// Default/Index Page
		/// </summary>
        public ActionResult Index()
        {
			return View();
        }

        public ActionResult Project()
        {
            return View();
        }

		/// <summary>
		/// About Page
		/// </summary>
        public ActionResult About()
        {
            KK.Models.Content content = KK.Models.Content.Get("Home", "About", "About Us");
			content.IsAdmin = IsAdmin;
            return View(content);
            
        }

        /// <summary>
        /// Blog Page
        /// </summary>
        /// <returns></returns>
        public ActionResult Blog()
        {
            ViewBag.Message = "Kenya Keys Blogs";

            return View();
        }
		
		/// <summary>
		/// Contact Page
		/// </summary>
		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}



        /// <summary>
        /// Contact Page
        /// </summary>
        public ActionResult Sponsorship()
        {

            ViewBag.Title = "Sponsorship";
            KK.Models.Content content = KK.Models.Content.Get("Home", "Sponsorship", "Sponsorships");
            content.IsAdmin = Request.IsAuthenticated && User.IsInRole("admin") ? true : false;
            return View(content);
        }

        /// <summary>
        /// In The News Page
        /// </summary>
        public ActionResult InTheNews()
        {
            ViewBag.Title = "In The News";
            KK.Models.Content content = KK.Models.Content.Get("Home", "InTheNews", "In The News");
            content.IsAdmin = Request.IsAuthenticated && User.IsInRole("admin") ? true : false;
            return View(content);
        }

        /// <summary>
        /// Donate Page
        /// </summary>
        public ActionResult Donate()
        {
            ViewBag.Title = "Donate & Get Involved";
            KK.Models.Content content = KK.Models.Content.Get("Home", "Donate", "Donate & Get Involved");
            return View(content);
        }

        /// <summary>
        /// Unauthorized Page
        /// </summary>
        public ActionResult Unauthorized()
        {
            return View();
        }

		/// <summary>
		/// Called for the User Login
		/// </summary>
		/// <param name="username">Username.</param>
		/// <param name="password">Password.</param>
        [HttpPost]
        public ActionResult Login(string username, string password)
        {   
            // Check if the login is valid
            string error = string.Empty;
            KK.User user = KK.User.Login(username, password, ref error);
            
            if (error == string.Empty && user.UserName != null)
            {
                FormsAuthenticationTicket authTicket = new FormsAuthenticationTicket(1, 
				                                                                     username, 
				                                                                     DateTime.Now, 
				                                                                     DateTime.Now.Add(new TimeSpan(1,0,0,0)), 
				                                                                     true, 
				                                                                     "roles="+String.Join(",", user.Roles));
                string encAuthTicket = FormsAuthentication.Encrypt(authTicket);
                HttpCookie authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encAuthTicket);
                if (Response.Cookies[FormsAuthentication.FormsCookieName] != null)
                {
                    Response.Cookies.Set(authCookie);
                }
                else
                {
                    Response.Cookies.Add(authCookie);
                }
            }
            else
            {
                ModelState.AddModelError("", error);
            }
            return RedirectToAction("Index", "Home");
        }

        public ContentResult Logout()
        {
            string username = User.Identity.Name;

            string result = string.Format("{{ result : 'success', data : {{ username :'{0}' }}", username);

            FormsAuthentication.SignOut();
            Session.Clear();

            return new ContentResult { Content = result }; ;
        }

    }
}

kenya_keys/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KK;
using KK.Models;
using System.Drawing;
using System.Drawing.Imaging;
using System.Drawing.Drawing2D;
using System.IO;

namespace KK.Controllers
{
    public class ProjectController : Controller
    {

		/// <summary>
		/// Index the specified project_id.
		/// </summary>
		/// <param name="project_id">Project_id.</param>
		public ActionResult Index(int? project_id = null)
        {
			if (project_id == null) {
				this.ViewData ["Projects"] = Project.GetAll ();
			} else {
				int selectedId = Convert.ToInt32(project_id);
				Project project = Project.GetById (Convert.ToInt32(project_id));
				if (project.ParentID != null) {
					project = Project.GetById (Convert.ToInt32 (project.ParentID));
				}

				this.ViewData ["Parent"] = project;
				List<Project> projects = project.GetChildren ();
				int index = 0;
				if (selectedId > 0) 
				{
					foreach (Project proj in projects) {
						index++;
						if (proj.ProjectID == project_id) 
						{
							proj.Selected = true;
							break;
						}
					}
				}


				this.ViewData ["Projects"] = projects;
			}
            return PartialView("Index");
        }

		/// <summary>
		/// Show the specified projectId.
		/// </summary>
		/// <param name="projectId">Project identifier.</param>
		public ActionResult Show(int projectId)
		{
			Project project = Project.GetById(projectId);
			Project parent = null;
			this.ViewData ["Project"] = project;

			if (project.ParentID != null) {
				parent = Project.GetById (Convert.ToInt32 (project.ParentID));
			}

			this.ViewData ["Parent"] = parent;


			return PartialView("Show");
		}

		/// <summary>
		/// Edit the specified project_id and parent_id.
		/// </summary>
		/// <param name="project_id">Project_id.</param>
		/// <param name="parent_id">Parent_id.</param>
		public ActionResult Edit(int? project_id = null, int? parent_id = null)
		{
			if (project_id != null)
			{
				KK.Models.Project project = Project.GetById(Convert.ToInt32(project_id));
				this.ViewData["Project"] = project;
			}

			if (parent_id != null) {
				this.ViewData ["Parent"] = Project.GetById (Convert.ToInt32 (parent_id));
			}
			return PartialView();
		}

		/// <summary>
		/// List this instance.
		/// </summary>
        public ActionResult List()
        {
            this.ViewData["Projects"] = Project.GetAll();
            return PartialView("List");
        }

		/// <summary>
		/// Save the specified project_id, proj_name, proj_display, photo_id, proj_html and parent_id.
		/// </summary>
		/// <param name="project_id">Project_id.</param>
		/// <param name="proj_name">Proj_name.</param>
		/// <param name="proj_display">Proj_display.</param>
		/// <param name="photo_id">Photo_id.</param>
		/// <param name="proj_html">Proj_html.</param>
		/// <param name="parent_id">Parent_id.</param>
		[HttpPost, ValidateInput(false)]
		public ContentResult Save(int? project_id, string proj_name, bool? proj_display, int? photo_id, string proj_html, int? parent_id)
        {
            Session.Remove("temp_image_data");
            Project project = new Project();
            if (project_id != null)
            {
                project = Project.GetById(Convert.ToInt32(project_id));
            }
			project.ParentID = parent_id;
            project.ProjectName = proj_name;
            project.ProjectHtml = proj_html;
            project.ProjectHide = proj_display == null ? false : Convert.ToBoolean(proj_display);
            if (photo_id != null) {
                project.ProjectImageID = Convert.ToInt32(photo_id);
            }
            
            project.Save();


            string result = string.Format("{{ result : 'success', data : {{ project_id :{0} }}", project.ProjectID);
            return new ContentResult { Content = result };  
        }

		/// <summary>
		/// Delete the specified projectID.
		/// </summary>
		/// <param name="projectID">Project I.</param>
        [HttpGet]
        public ContentResult Delete(int projectID)
        {
            Project.Delete(projectID);
			string result = string.Format("{{ \"result\" : \"success\", \"data\" : {{ \"project_id\" :{0} }} }}", projectID);
            return new ContentResult { Content = result }; 
        }

		/// <summary>
		/// Shows the page.
		/// </summary>
		/// <returns>The page.</returns>
		/// <param name="pageId">Page identifier.</param>
		public ActionResult ShowPage(int pageId)
		{
			this.ViewData["Page"] = ProjectPage.GetById(pageId);
			return PartialView();
		}

		/// <summary>
		/// Pages the edit.
		/// </summary>
		/// <returns>The edit.</returns>
		/// <param name="project_id">Project_id.</param>
		/// <param name="page_id">Page_id.</param>
		public ActionResult PageEdit(int project_id, int? page_id = null)
		{
			this.ViewData ["Project"] = Project.GetById (project_id);
			// get project pages
			List<KK.Models.ProjectPage> pages = ProjectPage.GetByAllByProjectId (project_id);
			this.ViewData ["PageIndex"] = pages.Count;

			if (page_id != null) {
				KK.Models.ProjectPage page = ProjectPage.GetById (Convert.ToInt32 (page_id));
				this.ViewData ["Page"] = page;
			}
			return PartialView("PageEdit");
		}


		[HttpPost, ValidateInput(false)]
		public JsonResult SavePage(int project_id, int page_index, string page_html, int? page_id = null)
		{

			ProjectPage page = new ProjectPage ();
			if (page_id != null) {
				page = ProjectPage.GetById (Convert.ToInt32 (page_id));
			}

			page.ProjectID = project_id;
			page.PageIndex = page_index;
			page.PageHtml = page_html;
			page.Save ();

			Response.ContentType = "application/json";
			return Json (page);
		}


		[HttpGet]
		public ContentResult DeletePage(int pageId)
		{

			ProjectPage Page = ProjectPage.GetById (pageId);
			ProjectPage.Delete (pageId);
			string result = string.Format("{{ \"result\" : \"success\", \"data\" : {{ \"project_id\" :{0} }} }}", Page.ProjectID);
			return new ContentResult { Content = result }; 
		}


       
    }
}

kenya_keys/Controllers/SlideController.cs
using KK.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace kenya_keys.Controllers
{
    public class SlideController : Controller
    {
        //
        // GET: /Admin/

        public ActionResult Index()
        {
            return View();
        }
        

        public ActionResult List()
        {
            ViewData["slides"] = KK.Models.Slide.GetAll();
            return PartialView();
        }


        public ActionResult Edit()
        {
            ViewData["slides"] = KK.Models.Slide.GetAll();
            return View();
        }

		public JsonResult Test(string value) {
			return Json(value);
		}


        [HttpPost]
		public JsonResult Save(string slide_text, int slide_index, int photo_id, int? slide_id = null)
        {
            Slide slide = new Slide();
			slide.SlideID = slide_id;
            slide.SlideText = slide_text;
            slide.SlideIndex = slide_index;
            slide.PhotoID = photo_id;
            slide.Save();
            return Json(slide);
        }
        


    }
}

kenya_keys/Views/Home/About.cshtml
@model KK.Models.Content
@{
    
}

@Html.Action("Display", "Content", Model)

kenya_keys/Views/Home/Blog.cshtml
@{
    ViewBag.Title = "Blog";
	bool IsAdmin = Convert.ToBoolean(ViewData["IsAdmin"]);
	List<KK.Models.Blog> blogs = (List<KK.Models.Blog>)ViewData ["blogs"];
	// @Html.Partial("~/Views/Blog/List.cshtml")
}

<h2>Blog</h2>

@if (IsAdmin) 
	{
		<a href="/Blog/Edit">Add</a>

	}
<script type="text/javascript">
		function blogPrev() {
			var limit = document.getElementById("blog_limit").value;
			var total = document.getElementById("blog_total").value;
			var offset = document.getElementById("blog_offset").value;

			execute(limit, total, parseInt(offset)-parseInt(limit));

		}

		function blogNext() {
			var limit = document.getElementById("blog_limit").value;
			var total = document.getElementById("blog_total").value;
			var offset = document.getElementById("blog_offset").value;	

			execute(limit, total, parseInt(offset)+parseInt(limit));
		}

		function execute(limit,total,offset) {
			$.ajax({
				url : '/Blog/List?offset='+offset+'&limit='+limit+'&total='+total,
				data : {
					limit : limit, 
					total : total,
					offset : offset
				},
				success : function(result) {
					document.getElementById("blog-content").innerHTML = result;
				},
				error : function(result) {
					console.log("error", result);
				}
			});
		}



	</script>	
<div id="blog-content"> 
	@Html.Action("List", "Blog", null)		
</div>

kenya_keys/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

kenya_keys/Views/Home/Donate.cshtml
@model KK.Models.Content
@{
    
}

@Html.Partial("~/Views/Content/Display.cshtml")

kenya_keys/Views/Home/InTheNews.cshtml
@model KK.Models.Content
@{
    
}

@Html.Partial("~/Views/Content/Display.cshtml")

kenya_keys/Views/Home/Index.cshtml
@{
    
}

<div>
    @Html.Action("List", "Slide", null)
</div>

<div>
    <div style="margin-left:10px; margin-top:15px;">
        <iframe src="//www.facebook.com/plugins/follow.php?href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FKenya-Keys%2F102788669795503&amp;width=450&amp;height=80&amp;colorscheme=light&amp;layout=standard&amp;show_faces=true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe>
        </div>
</div>

kenya_keys/Views/Home/Project.cshtml
@{
    ViewBag.Title = "Projects";
}

@section Scripts {
    <script src="/Scripts/js/Project.js" type="text/javascript"></script>
}

@section Styles {


	/* */
	div.projects { font-size:10pt; }

	/* Project Row */
	div.projects div.project-row { 
		height : 45px;
		clear : both; 
		margin-top:10px;

	 }
	/* Project tile */
	div.projects div.project-row div.project { 
		float : left; 
		width : 100px; 
		margin-left : 10px;
		border:solid 1px #dfdfdf ; 
		font-size : 9pt;
		font-weight : bold;
		webkit-touch-callout: none;
		-webkit-user-select: none;
		-khtml-user-select: none;
		-moz-user-select: none;
		-ms-user-select: none;
		user-select: none;
		background-color : #e2d4aa; 
		height : 45px;
		border : solid 3px brown;
		display:flex;
		text-align : center;
		justify-content: center; /* align horizontal */
		align-items: center; /* align vertical */

		cursor : pointer;
	}

	div.projects div.project-row div.project label {
		padding : 5px;
		color : #3D2220;
	}

	div#project-photo img { margin-left:20px;  }
	 

	



	div.projects div.project-row div.project.selected {
		border: solid 1px blue;
	}


}

@if (User.IsInRole("admin"))
{
    // ability to add project
    <a href="javascript:Project.edit();">[+] Add</a>
}

<table>
    <tr>
        <td valign="top" style="width:350px; padding-left:10px;">
        	<div id="project-menu">
        		 @Html.Action("Index", "Project", null)
        	</div>
            
        </td>
        <td style="width:650px;padding-left:25px;">
            <div id="project-content">
                <h1>Programs & Projects</h1>
                <div>
                    Each of Kenya Keys’ programs and projects is very carefully selected and implemented. The
                    needs in Kenya are so vast and far reaching, it is difficult to determine which projects should come first.
                    Our projects are education-based and selected on the following considerations: 
                </div>

                <ol>
                    <li>Most urgent need determined by our Kenyan Board of Directors.
                        Whether it’s the need for a new school, latrines, scholarships, or aid to a micro business, no one
                        knows the needs better than the people that live with the needs. Projects are
                        determined and run from the ground up, developing a strong sense of accountability
                        and ownership.
                    </li>
                    <li>How can donors get “the biggest bang for the buck”?
                        What project will be able to benefit the most people for the dollars spent? What will the long term benefits be?
                        What needs to be considered in terms of maintenance and follow up?
                    </li>
                    <li>What controls have been put in to place to “follow the money”? 
                        This is a very important piece. It must be very clear up front what the budget for the project is and
                        how monies will be allocated and accounted for.
                    </li>
                    <li>Will the beneficiaries be able to meet the 10% commitment? For every project
                        Kenya Keys undertakes the recipients sign a Partnership Agreement and agree to
                        pay 10% or more of the costs. This seems impossible to apply in such an impoverished
                        area, but it is critical to ensure a sense of partnership, pride, and accountability. In-
                        kind contributions are the primary source of this 10% commitment.
                        Click on one of the program or project links at the left to learn more.
                    </li>
                </ol>
            </div>
            
        </td>
    </tr>

</table>

kenya_keys/Views/Home/Sponsorship.cshtml
@model KK.Models.Content
@{
    
}

@Html.Partial("~/Views/Content/Display.cshtml")

kenya_keys/Views/Home/Unauthorized.cshtml
@{
    /// Page redirect for the admin
    ViewBag.Title = "Unauthorized";
}

<h2>Unauthorized</h2>
<div>You are not allowed to view this page.</div>